---
title: Bradley Sansom
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: 
bio: Hi! My name is Bradley, and this is apparently my website.
description: The personal website of world-renowmed style icon, Bradley Sansom
locale: en_GB
baseurl: ''
url: ''
disqus_shortname: default
analytics-id: default
twitter: bradleysans
pinterest: bradleysans
github: bradleysansom
location: Bradford, UK
email: b-sansom@outlook.com
background_image: "/images/bg.jpg"
slapform_thankyou_page: "/thank-you"
permalink: "/blog/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
gems:
- jekyll-mentions
- jekyll-sitemap
- jekyll-feed
- jekyll-gist
- jekyll-paginate
paginate: 6
paginate_path: "/blog/page:num/"
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
- old
