---
title: Bradley Sansom
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: I make things, sometimes.
baseurl: ''
url: ''
github_username: bradleysansom
email: bradley-sansom@outlook.com
flickr: bradleysans
theme: minima
plugins:
- jekyll-feed
- name: Cache
  uses: actions/cache@v3.2.2
- uses: chrisreddington/rss-parser-action@main
  with:
    # Branch Prefix is used when the script_output is set to pull_request.
    # This is the prefix to the branch name which is created (i.e. each new feed item will be created in  a new git branch. The branch will have a prefix using this input).
    branch_prefix: 'create-project-post'

    # Extension is used when the script_output is set to pull_request.
    # This is the extension to the files which are created (i.e. each new feed item will be a new file with this extension).
    extension: 'html'

    # URL of the RSS feed to parse. Required.
    # Must be a valid URL, starting with http or https.
    feed_url: 'https://bradleysans.uk/projects/posts.xml'

   

    # Last parsed file is used when the script_output is set to pull_request.
    # This is the file which will be used to store the last parse information for each configuration.
    # 
    # A configuration is a combination of the inputs to the action. An example can be found in the repository for this action, under the .github folder, in a branch called 'twitter-config'.
    # The file is deliberately not committed directly into main, in case there are branch protection rules in place. Instead, it's up to the user to merge the file into main.
    last_parsed_file: 'parses.md'

    # The desired action to take once this action has executed. Required.
    # Must be one of: issue, json, pull_request
    script_output: 'pull_request'

    # Subfolder is used when the script_output is set to pull_request.
    # This is the subfolder where files will be created (i.e. each new feed item will be a new file in that subfolder).
    subfolder: 'projects'

