on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Project page create
    steps:
      - name: Hello world action step
        id: hello
        uses: chrisreddington/rss-parser-action@main
        with:
          branch_prefix: 'project'
          extension: '.html'
          feed_url: 'https://bradleysans.uk/projects/posts.xml'
          last_parsed_file: 'last_parsed.json'
          script_output: 'pull_request'
          subfolder: 'projects/'

      
