on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Project page create
    steps:
      - name: Hello world action step
        id: hello
        uses: bradleysansom/proj@v1
          with:
            milliseconds: 1000

      
